display_name: Lapse
package_name: lapse
license: GPL-3.0
icon: assets/icons/icon-other.png
generic_name: Flashcard Study App
categories:
  - Education
keywords:
  - flashcards
  - spaced repetition
  - study
startup_notify: true
