display_name: Lapse
package_name: lapse
maintainer:
  name: Pairadux
  email: pairadux@users.noreply.github.com
priority: optional
section: x11
installed_size: 35000
icon: assets/icons/icon-other.png
generic_name: Flashcard Study App
categories:
  - Education
keywords:
  - flashcards
  - spaced repetition
  - study
startup_notify: true
